#ifndef DESKTOP_OBJECT_ORIENTED_DESIGN_4WEEK_PRACTICE_CALC_H_
#define DESKTOP_OBJECT_ORIENTED_DESIGN_4WEEK_PRACTICE_CALC_H_

int calc(char op, int num_1, int num_2);

#endif  // DESKTOP_OBJECT_ORIENTED_DESIGN_4WEEK_PRACTICE_CALC_H_
